project:
  type: website

website:
  title: "Spooky Stats"
  sidebar:
    style: 'docked'
    search: false
    contents:
      - href: index.qmd
        text: Home
      - section: Basics
        contents:
        - href: 01_quick_bayes_introduction.qmd
        - href: 02_mcmc_tech.qmd
        - href: 03_Model-Checking.qmd
      - section: Spooky Stuff!
        contents:
        - href: ex01_single-parameter.qmd
        - href: ex02_hierarchical.qmd
        - href: ex03_linear-models.qmd
        - href: ex04_logit-occs.qmd
        # - href: ex05_process-models.qmd
        # - href: ex06_count_data.qmd
      - section: Other stuff
        contents:
        - href: s01_additional_resources.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-location: right



